name: "Build"

on:
  # Build on push to master
  push:
    branches:
      - master

  # Do not build on internal pull requests
  # pull_request:

  # Do not allow to trigger for external PRs
  # workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "result"
      - run: |
          nix build .#cashewnix -o result
  build-aarch64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt-get install -y qemu-user-static
      - uses: cachix/install-nix-action@v25
        with:
          extra_nix_config: |
            system = aarch64-linux
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "result"
      - run: |
          nix build .#cashewnix -o result
