name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
      - uses: DeterminateSystems/magic-nix-cache-action@v6
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          pathsToPush: "result"
      - run: |
          nix flake check
