name: Test

on:
  pull_request:
  workflow_dispatch:

jobs:
  nix_flake_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: cachix/install-nix-action@v31
        with:
          enable_kvm: true
          extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"
      - uses: cachix/cachix-action@v17
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - run: |
          nix flake check
