name: Update Flake

on:
  schedule:
    # every friday at 3 UTC
    - cron: "0 3 * * 5"
  workflow_dispatch:
jobs:
  updates:
    name: "Update the flake.lock"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: cachix/install-nix-action@v30
      - uses: cachix/cachix-action@v14
        with:
          name: foldu
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
      - name: "flake.lock: Update"
        run: |
          git config user.name 'github-actions'
          git config user.email 'action@github.com'
          nix flake update --commit-lock-file
          nix flake check
          git push
